"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { animate, motion } from "framer-motion";
import { BarChart3, CheckCircle2, Clipboard, Download, Flag, RefreshCw, Target, TriangleAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";

type Feedback = { summary: string; strengths: string[]; gaps: string[]; next: string[] };
type Report = { candidate: { member: { name: string; jobRole: string; yearsExperience: number; education: string } }; feedback: Feedback; questionsAsked: Array<{ day: number; question: string; topic: string; difficulty: string }>; messages: Array<{ role: "interviewer" | "candidate"; content: string }>; topicsCovered: string[]; difficultyProgression: string[]; answerEvaluations: Array<{ score: number; strengths: string[]; gaps: string[] }>; topicScores: Record<string, number[]>; scores: { overall: number; technicalKnowledge: number; problemSolving: number; communication: number }; recommendedDays: Array<{ day: number; title: string; score: number }> };

function Score({ value }: { value: number }) { const [shown, setShown] = useState(0); useEffect(() => { const control = animate(0, value, { duration: 0.75, onUpdate: (latest) => setShown(Math.round(latest)) }); return () => control.stop(); }, [value]); return <span>{shown}</span>; }
function initials(name: string) { return name.split(" ").map((part) => part[0]).join("").slice(0, 2); }
function readiness(score: number) { return score >= 80 ? "Interview ready" : score >= 60 ? "Developing strongly" : "Foundation in progress"; }
function Radar({ scores }: { scores: Report["scores"] }) { const values = [scores.technicalKnowledge, scores.problemSolving, scores.communication, scores.overall]; const points = values.map((value, index) => { const angle = (-90 + index * 90) * Math.PI / 180; const radius = 57 * value / 100; return `${75 + Math.cos(angle) * radius},${75 + Math.sin(angle) * radius}`; }).join(" "); return <div className="relative mx-auto h-44 w-44"><svg viewBox="0 0 150 150" className="h-full w-full overflow-visible"><polygon points="75,18 132,75 75,132 18,75" fill="hsl(var(--surface-raised) / .38)" stroke="hsl(var(--line) / .13)" /><polygon points="75,37 113,75 75,113 37,75" fill="none" stroke="hsl(var(--line) / .1)" /><line x1="75" y1="18" x2="75" y2="132" stroke="hsl(var(--line) / .1)" /><line x1="18" y1="75" x2="132" y2="75" stroke="hsl(var(--line) / .1)" /><motion.polygon initial={{ opacity: 0, scale: 0.6, transformOrigin: "75px 75px" }} animate={{ opacity: 0.85, scale: 1 }} points={points} fill="hsl(var(--signal) / .3)" stroke="hsl(var(--signal))" strokeWidth="2" /></svg><span className="absolute left-1/2 top-0 -translate-x-1/2 text-[10px] text-text-muted">Knowledge</span><span className="absolute right-0 top-1/2 -translate-y-1/2 text-[10px] text-text-muted">Problem</span><span className="absolute bottom-0 left-1/2 -translate-x-1/2 text-[10px] text-text-muted">Communication</span><span className="absolute left-0 top-1/2 -translate-y-1/2 text-[10px] text-text-muted">Overall</span></div> }

export default function ReportPage() {
  const router = useRouter(); const { toast } = useToast(); const [report, setReport] = useState<Report | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { const timer = window.setTimeout(() => { try { const saved = localStorage.getItem("interviewos.latestReport"); if (saved) setReport(JSON.parse(saved)); } catch { setReport(null); } finally { setLoading(false); } }, 160); return () => window.clearTimeout(timer); }, []);
  const restart = () => { localStorage.removeItem("interviewos.latestReport"); router.push("/dashboard"); };
  const copy = async () => { if (!report) return; await navigator.clipboard.writeText([report.feedback.summary, "Strengths", ...report.feedback.strengths, "Knowledge gaps", ...report.feedback.gaps, "Next steps", ...report.feedback.next].join("\n")); toast({ title: "Feedback copied", description: "The interview feedback is ready to share." }); };
  if (loading) return <div className="space-y-6"><div className="glass rounded-2xl p-7"><Skeleton className="h-14 w-2/3" /><Skeleton className="mt-4 h-4 w-1/3" /></div><div className="grid gap-6 lg:grid-cols-2"><Skeleton className="h-80 rounded-xl" /><Skeleton className="h-80 rounded-xl" /></div></div>;
  if (!report) return <div className="glass flex min-h-[62vh] flex-col items-center justify-center rounded-2xl px-6 text-center"><BarChart3 className="h-9 w-9 text-text-faint" /><h1 className="mt-5 text-2xl font-semibold">No completed interview yet</h1><p className="mt-2 max-w-md text-sm leading-relaxed text-text-muted">Complete an interview from the candidate dashboard to generate a detailed readiness report.</p><Button className="mt-6" onClick={restart}>Choose a candidate</Button></div>;
  const categories = [["Technical knowledge", report.scores.technicalKnowledge], ["Problem solving", report.scores.problemSolving], ["Communication", report.scores.communication]] as const;
  const topicScores = Object.entries(report.topicScores).map(([topic, scores]) => [topic, Math.round(scores.reduce((sum, score) => sum + score, 0) / scores.length * 20)] as const);
  return <div className="space-y-6"><motion.header initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass flex flex-col gap-6 rounded-2xl p-6 sm:p-8 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-center gap-4"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-gradient-to-br from-signal to-pulse text-sm font-semibold text-ink">{initials(report.candidate.member.name)}</span><div><p className="text-xl font-semibold tracking-tight">{report.candidate.member.name}</p><p className="mt-1 text-sm text-text-muted">{report.candidate.member.jobRole} · {report.candidate.member.yearsExperience} years experience</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="signal">{readiness(report.scores.overall)}</Badge><Badge variant="outline">{report.questionsAsked.length} questions · {new Set(report.questionsAsked.map((question) => question.day)).size} days</Badge></div></div></div><div className="flex flex-wrap gap-2"><Button variant="secondary" size="sm" onClick={copy}><Clipboard />Copy feedback</Button><Button variant="secondary" size="sm" onClick={() => window.print()}><Download />Print report</Button><Button size="sm" onClick={restart}><RefreshCw />Restart interview</Button></div></motion.header>
    <section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]"><div className="glass rounded-xl p-6"><p className="text-xs font-semibold uppercase tracking-[.16em] text-signal">Overall interview score</p><div className="mt-5 flex flex-col items-center gap-4 sm:flex-row"><div className="relative flex h-36 w-36 items-center justify-center rounded-full" style={{ background: `conic-gradient(hsl(var(--signal)) ${report.scores.overall * 3.6}deg, hsl(var(--surface-raised)) 0deg)` }}><div className="flex h-28 w-28 flex-col items-center justify-center rounded-full bg-surface"><span className="text-3xl font-semibold"><Score value={report.scores.overall} /></span><span className="text-[10px] uppercase tracking-[.16em] text-text-faint">out of 100</span></div></div><div><p className="text-lg font-semibold">{readiness(report.scores.overall)}</p><p className="mt-2 max-w-xs text-sm leading-relaxed text-text-muted">A senior-interviewer readout based on the actual answers, curriculum coverage, and difficulty progression.</p></div></div></div><div className="glass rounded-xl p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Skill profile</p><p className="mt-1 text-xs text-text-muted">Relative signal across the completed interview</p></div><Target className="h-4 w-4 text-signal" /></div><div className="mt-3 grid items-center gap-4 sm:grid-cols-[180px_1fr]"><Radar scores={report.scores} /><div className="space-y-4">{categories.map(([label, value]) => <div key={label}><div className="flex justify-between text-xs"><span className="text-text-muted">{label}</span><span className="font-mono">{value}</span></div><Progress value={value} className="mt-2" /></div>)}</div></div></div></section>
    <section className="grid gap-6 lg:grid-cols-2"><div className="glass rounded-xl p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Evaluator summary</h2><p className="mt-1 text-xs text-text-muted">Based on the complete session</p></div><CheckCircle2 className="h-4 w-4 text-mint" /></div><p className="mt-5 text-sm leading-relaxed text-text-primary">{report.feedback.summary}</p><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-mint">Strengths</p><ul className="mt-3 space-y-2">{report.feedback.strengths.map((item) => <li key={item} className="flex gap-2 text-sm leading-relaxed text-text-muted"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-mint" />{item}</li>)}</ul></div><div><p className="text-xs font-semibold uppercase tracking-[.13em] text-pulse">Knowledge gaps</p><ul className="mt-3 space-y-2">{report.feedback.gaps.map((item) => <li key={item} className="flex gap-2 text-sm leading-relaxed text-text-muted"><TriangleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-pulse" />{item}</li>)}</ul></div></div></div><div className="glass rounded-xl p-6"><h2 className="text-sm font-semibold">Topic-wise performance</h2><p className="mt-1 text-xs text-text-muted">Scores reflect evaluation signals in each topic.</p><div className="mt-6 space-y-4">{topicScores.length ? topicScores.map(([topic, score]) => <div key={topic}><div className="flex justify-between gap-4 text-xs"><span className="truncate text-text-muted">{topic}</span><span className="font-mono text-text-primary">{score}</span></div><Progress value={score} className="mt-2" /></div>) : <p className="text-sm text-text-faint">Topic performance is unavailable for this session.</p>}</div></div></section>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><div className="glass rounded-xl p-6"><div className="flex items-center justify-between"><div><h2 className="text-sm font-semibold">Interview timeline</h2><p className="mt-1 text-xs text-text-muted">How the interviewer adapted during the session</p></div><Flag className="h-4 w-4 text-signal" /></div><div className="mt-6 space-y-0">{report.questionsAsked.map((question, index) => <motion.div initial={{ opacity: 0, x: -8 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: index * .045 }} key={`${question.day}-${index}`} className="relative flex gap-4 border-l border-line/15 pb-5 pl-5 last:pb-0"><span className="absolute -left-[5px] top-1 h-2.5 w-2.5 rounded-full bg-signal" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-[10px] text-text-faint">Q{index + 1} · DAY {question.day}</span><Badge variant={question.difficulty === "Hard" ? "signal" : "outline"} className="text-[10px]">{question.difficulty}</Badge></div><p className="mt-1 truncate text-sm font-medium">{question.topic}</p></div></motion.div>)}</div></div><div className="glass rounded-xl p-6"><h2 className="text-sm font-semibold">Personalized next steps</h2><p className="mt-1 text-xs text-text-muted">A focused learning plan for the next interview.</p><div className="mt-5 space-y-3">{report.feedback.next.map((item, index) => <div key={item} className="rounded-lg border border-line/10 bg-surface-raised/35 p-3"><span className="font-mono text-[10px] text-signal">0{index + 1}</span><p className="mt-1 text-sm leading-relaxed text-text-muted">{item}</p></div>)}</div><div className="mt-6 border-t border-line/10 pt-5"><p className="text-xs font-semibold uppercase tracking-[.13em] text-pulse">Recommended curriculum revision</p><div className="mt-3 space-y-2">{report.recommendedDays.map((day) => <div key={day.day} className="flex items-center justify-between rounded-lg bg-surface-raised/35 px-3 py-2.5"><span className="min-w-0 pr-3 text-xs text-text-primary">Day {day.day} · {day.title}</span><span className="font-mono text-[11px] text-pulse">{day.score}</span></div>)}</div></div></div></section></div>;
}
